### ISSUE TITLE
Which SYNTHIA dataset have you used?

### ISSUE THREAD

**Issue by junhocho** [BIT-DA/RIPU#2]
Hi, trying your code with [SYNHIA](https://synthia-dataset.net/downloads/), there are lots of different types of SYNTHIA datasets. Your paper mentioned that training data has 9400 images with 16 classes but I am afraid I still cannot judge which data is what you used.

**Comment by BinhuiXie** [comment]
Hi @junhocho 

Thanks for your attention.

We use the version of [SYNTHIA-RAND-CITYSCAPES (CVPR16)](http://synthia-dataset.net/download/808/).

**Comment by junhocho** [comment]
Hi, looks like I have another problem here.  (FYI, I managed to train for GTAV->CITYSCPAES. but not in synthia->CITYSCAPES)

With the data you mentioned,
ran `python datasets/generate_synthia_label_info.py -d datasets/synthia -o datasets/synthia/` and this works fine with following console output
```
100%|███████████████████████████████| 9400/9400 [01:07<00:00, 140.15it/s]
```
and 
```
.
├── RAND_CITYSCAPES
├── synthia_label_info.p
```
for the directory structure in synthia

Then when I run some scripts in `synthia_to_cityscapes.sh`, this is what I get in console
```
<skip>
100%|███████████████████████████████████| 2975/2975 [06:47<00:00,  7.30it/s]
Compose(
    <core.datasets.transform.Resize object at 0x7f7ecc7efd30>
    <core.datasets.transform.ToTensor object at 0x7f7ecc7efcd0>
    <core.datasets.transform.Normalize object at 0x7f7ecc7efc10>
)
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 259, in main
    train(cfg)
  File "train.py", line 67, in train
    src_train_data = build_dataset(cfg, mode='train', is_source=True)
  File "/home/junho/RIPU/core/datasets/build.py", line 39, in build_dataset
    dataset = DatasetCatalog.get(cfg.DATASETS.SOURCE_TRAIN, mode, num_classes=cfg.MODEL.NUM_CLASSES,
  File "/home/junho/RIPU/core/datasets/dataset_path_catalog.py", line 53, in get
    return synthiaDataSet(args["root"], args["data_list"], max_iters=max_iters, num_classes=num_classes,
  File "/home/junho/RIPU/core/datasets/synthia.py", line 56, in __init__
    c_file = self.label_to_file[c][ind[c]]
IndexError: list index out of range
```
This looks causing error in 
```
    src_train_loader = DataLoader(src_train_data, batch_size=cfg.SOLVER.BATCH_SIZE, shuffle=True, num_workers=1,
                                  pin_memory=True, drop_last=True)
```
, there is something wrong when loading source data.

I am debugging here (`synthia.py`) and it fails when `c==8` thus `self.label_to_file[c]` returning `[]` and causing empty index error.
```
                    if ind[c] > (len(self.label_to_file[c]) - 1):                                                                                                                                                                                                                                                                               np.random.shuffle(self.label_to_file[c])                                                                                                                                                                                                                                                                                ind[c] = ind[c] % (len(self.label_to_file[c]) - 1)

                    try:
                        c_file = self.label_to_file[c][ind[c]]
                    except:
                        import pdb;pdb.set_trace()
                    tmp_list.append(c_file)
                    ind[c] = ind[c] + 1
                    cur_class_dist[self.file_to_label[c_file]] += 1



(Pdb) [len(e) for e in self.label_to_file]
[9398, 2900, 9394, 0, 0, 0, 0, 0, 0, 9398, 0, 0, 0, 0, 0, 0]
```

Any idea?

**Comment by BinhuiXie** [comment]
u might try the provided file [here](https://github.com/BIT-DA/RIPU/blob/main/datasets/synthia_label_info.p)

**Comment by junhocho** [comment]
Thx! this makesthe training work.
